<a href="https://colab.research.google.com/github/ramanji567/Sql-Joins/blob/main/Sql_joints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tables of Schemas students,enrollments,grades

In [1]:
import sqlite3
import pandas as pd

# Using a 'with' statement ensures the connection is properly closed
# even if errors occur, preventing 'database is locked' errors.
conn = sqlite3.connect('sql_joins.db')
cursor = conn.cursor()

    # Drop tables if they exist to ensure a clean slate on re-executi

cursor.execute(
        '''CREATE TABLE IF NOT EXISTS students(
          student_id INTEGER PRIMARY KEY AUTOINCREMENT,
          name TEXT,
          email TEXT,
          City TEXT
        )''')
cursor.execute(
        '''CREATE TABLE IF NOT EXISTS Enrollments(
          enrollment_id INTEGER PRIMARY KEY,
          student_id INTEGER,
          course_name TEXT,
          enrollment_date TEXT,
          FOREIGN KEY (student_id) REFERENCES students(student_id)
        )'''
    )
cursor.execute(
        '''CREATE TABLE IF NOT EXISTS grades(
          grade_id INTEGER PRIMARY KEY,
          student_id INTEGER,
          course_name TEXT,
          score INTEGER,
          FOREIGN KEY (student_id) REFERENCES students(student_id)
        )''')

students_data = [
        ('Alice','alice@email.com','Mumbai'),
        ('Bob','bob@email.com','Delhi'),
        ('Carol','carole@email.com','Bangalore'),
        ('David','david@email.com','Chennai'),
        ('Emma','emma@email.com','Pune')
    ]
cursor.executemany('INSERT INTO students(name,email,city) VALUES(?,?,?)',students_data)

enrollments_data = [
        (101,1,'Python','2024-01-15'),
        (102,1,'SQL','2024-02-01'),
        (103,2,'Data Science','2024-01-20'),
        (104,3,'Python','2024-02-10'),
        (105,3,'Machine Learning','2024-01-25'),
    ]

cursor.executemany('''INSERT INTO enrollments(enrollment_id,student_id,course_name,enrollment_date)
    VALUES(?,?,?,?)''',enrollments_data)

grades_data = [
        (201,1,'Python',85),
        (202,1,'SQL',90),
        (203,2,'Data Science',78),
        (204,4,'Web Development',88)
    ]

cursor.executemany('''INSERT INTO grades(grade_id,student_id,course_name,score)
    VALUES(?,?,?,?)''',grades_data)

    # Commit changes within the 'with' block
conn.commit()

# The connection is automatically closed when exiting the 'with' block

In [3]:
conn = sqlite3.connect('sql_joins.db')
cursor = conn.cursor()
query = 'SELECT * FROM students'
cursor.execute(query)
cursor.fetchall()

[(1, 'Alice', 'alice@email.com', 'Mumbai'),
 (2, 'Bob', 'bob@email.com', 'Delhi'),
 (3, 'Carol', 'carole@email.com', 'Bangalore'),
 (4, 'David', 'david@email.com', 'Chennai'),
 (5, 'Emma', 'emma@email.com', 'Pune')]

In [4]:
conn = sqlite3.connect('sql_joins.db')
cursor = conn.cursor()
query = 'SELECT * FROM enrollments'
cursor.execute(query)
cursor.fetchall()

[(101, 1, 'Python', '2024-01-15'),
 (102, 1, 'SQL', '2024-02-01'),
 (103, 2, 'Data Science', '2024-01-20'),
 (104, 3, 'Python', '2024-02-10'),
 (105, 3, 'Machine Learning', '2024-01-25')]

In [5]:
conn = sqlite3.connect('sql_joins.db')
cursor = conn.cursor()
query = 'SELECT * FROM grades'
cursor.execute(query)
cursor.fetchall()

[(201, 1, 'Python', 85),
 (202, 1, 'SQL', 90),
 (203, 2, 'Data Science', 78),
 (204, 4, 'Web Development', 88)]

Task 1:Basic Joins
    
    1.INNER JOIN

In [6]:
conn = sqlite3.connect('sql_joins.db')
cursor = conn.cursor()
query = '''SELECT s.name,e.course_name
    FROM students  AS s
    INNER JOIN enrollments  AS e ON s.student_id = e.student_id'''
cursor.execute(query)
cursor.fetchall()

[('Alice', 'Python'),
 ('Alice', 'SQL'),
 ('Bob', 'Data Science'),
 ('Carol', 'Python'),
 ('Carol', 'Machine Learning')]

INNER JOIN means extra the data both tables have common id only extract common data only in both columns

2.Left JOIN

In [7]:
conn = sqlite3.connect('sql_joins.db')
cursor = conn.cursor()
query = '''SELECT s.name ,e.course_name
FROM students AS s
LEFT JOIN enrollments AS e ON s.student_id = e.student_id'''
cursor.execute(query)
cursor.fetchall()
#

[('Alice', 'Python'),
 ('Alice', 'SQL'),
 ('Bob', 'Data Science'),
 ('Carol', 'Machine Learning'),
 ('Carol', 'Python'),
 ('David', None),
 ('Emma', None)]

LEFT JOIN

     In left join to extra the from left table to match with right table fill with right table data if there is no match in right table fill with null values

Task 2 : Multiple Table Joins

In [10]:
conn = sqlite3.connect('sql_joins.db')
cursor = conn.cursor()
query = '''SELECT s.name,e.course_name,g.score
FROM students AS s
LEFT JOIN enrollments AS e ON s.student_id = e.student_id
LEFT JOIN grades AS g ON s.student_id = g.student_id  AND e.course_name = g.course_name'''
cursor.execute(query)
cursor.fetchall()

[('Alice', 'Python', 85),
 ('Alice', 'SQL', 90),
 ('Bob', 'Data Science', 78),
 ('Carol', 'Machine Learning', None),
 ('Carol', 'Python', None),
 ('David', None, None),
 ('Emma', None, None)]

MULTIPLE JOINS

        in this query two left joins are extra the data all from left table match right table when there is no match fill null values in this query

Task 3 :Understanding Joins and Normalization

1.Normalization

    *  Normalization is the process of organizing data in a database
    to redudancy and improve data integrity

    the split student information into three tables becacuse instead
    of students like (name and address )every time they enroll in a
    new course, you store it once this saves storage space
    
    Data consitency :
    if a student changes their address , you only need to update one
    row in one table .In a single large table,you  would have to find
    and update every singel row

2.when to use the joins
   
       1.Use inner join when : you only want to retrive the records
       that have matching values in both tables


       2.use left join when : you only want to retrive the records
        from left table and matching with recods from right table if
        there is  no fill with null values

In [11]:
import pandas as pd
conn = sqlite3.connect('sql_joins.db')
query = '''SELECT * FROM students'''
student_df = pd.read_sql_query(query,conn)
student_df

   student_id   name             email       City
0           1  Alice   alice@email.com     Mumbai
1           2    Bob     bob@email.com      Delhi
2           3  Carol  carole@email.com  Bangalore
3           4  David   david@email.com    Chennai
4           5   Emma    emma@email.com       Pune

In [12]:
conn = sqlite3.connect('sql_joins.db')
query = '''SELECT * FROM enrollments'''
enrollments_df = pd.read_sql_query(query,conn)
enrollments_df

   enrollment_id  student_id       course_name enrollment_date
0            101           1            Python      2024-01-15
1            102           1               SQL      2024-02-01
2            103           2      Data Science      2024-01-20
3            104           3            Python      2024-02-10
4            105           3  Machine Learning      2024-01-25

In [14]:
conn = sqlite3.connect('sql_joins.db')
query = '''SELECT * FROM grades'''
grades_df = pd.read_sql(query,conn)
grades_df

   grade_id  student_id      course_name  score
0       201           1           Python     85
1       202           1              SQL     90
2       203           2     Data Science     78
3       204           4  Web Development     88

In [16]:
result = pd.merge(student_df,enrollments_df,on = 'student_id',how ='left' )
result

,student_id,name,email,City,enrollment_id,course_name,enrollment_date
0,1,Alice,alice@email.com,Mumbai,101.0,Python,2024-01-15
1,1,Alice,alice@email.com,Mumbai,102.0,SQL,2024-02-01
2,2,Bob,bob@email.com,Delhi,103.0,Data Science,2024-01-20
3,3,Carol,carole@email.com,Bangalore,104.0,Python,2024-02-10
4,3,Carol,carole@email.com,Bangalore,105.0,Machine Learning,2024-01-25
5,4,David,david@email.com,Chennai,NaN,NaN,NaN
6,5,Emma,emma@email.com,Pune,NaN,NaN,NaN

In [17]:
result2 = pd.merge(result,grades_df,on = ['student_id','course_name'],how = 'left')
result2

,student_id,name,email,City,enrollment_id,course_name,enrollment_date,grade_id,score
0,1,Alice,alice@email.com,Mumbai,101.0,Python,2024-01-15,201.0,85.0
1,1,Alice,alice@email.com,Mumbai,102.0,SQL,2024-02-01,202.0,90.0
2,2,Bob,bob@email.com,Delhi,103.0,Data Science,2024-01-20,203.0,78.0
3,3,Carol,carole@email.com,Bangalore,104.0,Python,2024-02-10,NaN,NaN
4,3,Carol,carole@email.com,Bangalore,105.0,Machine Learning,2024-01-25,NaN,NaN
5,4,David,david@email.com,Chennai,NaN,NaN,NaN,NaN,NaN
6,5,Emma,emma@email.com,Pune,NaN,NaN,NaN,NaN,NaN